### ISSUE TITLE
About LoRA layers

### ISSUE THREAD

**Issue by lxr-1204** [ai4colonoscopy/IntelliScope#2]
Hello, Dr. Ji, and thank you for your excellent work! This research is both solid and profoundly meaningful. 

Upon carefully reviewing your code, I noticed that you aimed to set the **mm_mlp_adapter** as trainable. To achieve this, you first [froze all parameters](https://github.com/ai4colonoscopy/IntelliScope/blob/4e17c373a5fbec3e64141fa7180153f8e61fb74b/colongpt/train/train.py#L321) and then selectively [unfroze the **mm_mlp_adapter**](https://github.com/ai4colonoscopy/IntelliScope/blob/4e17c373a5fbec3e64141fa7180153f8e61fb74b/colongpt/train/train.py#L323). 
```
    model.config.tune_mm_mlp_adapter = training_args.tune_mm_mlp_adapter = model_args.tune_mm_mlp_adapter
    if model_args.tune_mm_mlp_adapter:
        model.requires_grad_(False)
        for p in model.get_model().mm_projector.parameters():
            p.requires_grad = True
```
However, it seems that during this process, the parameters of the LoRA layers were also unintentionally frozen, and they were not explicitly unfrozen in the subsequent code.

Could you kindly provide me with some guidance? Once again, I deeply appreciate your outstanding work!

**Comment by GewelsJI** [comment]
Hi, @lxr-1204 

Thanks for your reminder. You are right. 

My student Jingyi messed up code version here. We will update a new code in next week, and let you know then. Or if you are hurry up, just manually turn on the LoRA training, which is not very hard to change the code.

Best,
Daniel

**Comment by GewelsJI** [comment]
Hi @lxr-1204

Happy new year, bro.

Sorry for late reply and thanks for your patience. New ColonGPT with enhanced performance has been announced right now. The training code is disclosed for your convenient use. As well, further details can be found in our arXiv-v2 document (https://arxiv.org/abs/2410.17241v2). 

Please feel free to contact us if you encounter any questions.

Best,
Daniel.
