### ISSUE TITLE
fine tune upon your pertained weight

### ISSUE THREAD

**Issue by NyKxo1** [ai4colonoscopy/IntelliScope#3]
Thank you for your impressive work! I am particularly interested in building upon your pre-trained weights, which integrate LLM and LoRA. Could you kindly provide a tutorial or guidance on how to perform further fine-tuning using these weights?

**Comment by GewelsJI** [comment]
Hi @NyKxo1 

We’re currently working hard to integrate more lightweight LLMs this month, and the stronger models will be ready for release next month. Just hang tight and be patient. We’ll also be providing detailed fine-tuned tutorials as soon as they’re ready, and we’ll let you know right away. Stay tuned!

**Comment by GewelsJI** [comment]
Hello, @NyKxo1 

Our new code has been released. Feel free to fine-tune it on your data.

Best regards,
Daniel.
