### ISSUE TITLE
Missing File for Model Training

### ISSUE THREAD

**Issue by chxhe** [ai4colonoscopy/IntelliScope#4]
Where is the "colongpt/train/train.py" mentioned in guideline-for-ColonGPT.md?

**Comment by GewelsJI** [comment]
We are working on integrating and training more models in our framework. Please stay tuned, and I will let you know if we've done. Probably next month.

**Comment by GewelsJI** [comment]
Hi @chxhe 

We've prepared the new training code for ColonGPT. You can try it right now. Reach out me if you have any questions.

Best,
Daniel
